#!/usr/bin/env python
###############################################################################
# Runs the Spark Test Server from the source file                             #
###############################################################################
###############################################################################
#                                   IMPORTS                                   #
###############################################################################
import xml.etree.ElementTree
import sys
import os
###############################################################################
#                                  CONSTANTS                                  #
###############################################################################
POM_FNAME = "pom.xml"
JAR_FILE_TEMPLATE = "target/%(artifact_id)s-%(version)s.jar"
XMLNS = "http://maven.apache.org/POM/4.0.0"
###############################################################################
#                                    CODE                                     #
###############################################################################
def project_path():

	script_dir = os.path.dirname(sys.argv[0])
	return os.path.realpath(script_dir)

def pom_findAll(node, search):

	return node.findall('{%s}%s' % (XMLNS, search) )

def project_jarfile():

	pom_path = os.path.join(project_path(), POM_FNAME)
	tree = xml.etree.ElementTree.parse(pom_path)

	root = tree.getroot()

	try:
		artifact_id = pom_findAll(root, "artifactId")[0].text
		version = pom_findAll(root, "version")[0].text
	except IndexError as e:
		raise RuntimeError("pom.xml is missing required attributes")

	return os.path.join(
		project_path(),
		JAR_FILE_TEMPLATE % {
			'artifact_id': artifact_id, 'version': version
		}
	)

def become_server(jar_file):

	os.execvpe(
		'java',
		['java', '-jar', jar_file] + sys.argv[1:],
		os.environ
	)

if __name__ == '__main__':

	try:
		jar_file = project_jarfile()
	except IOError as e:
		sys.stderr.write('Error finding project jar file\n')
		exit(-1)
	except RuntimeError as e:
		sys.stderri.write("%s\n" % str(e))
		exit(-1)

	if not os.path.exists(jar_file):
		sys.stderr.write("Jar file %s not found\n" % jar_file)
		exit(-1)

	try:
		become_server(jar_file)
	except OSError as e:
		sys.stderr.write("%s\n" % str(e))
		exit(-1)